version: '3.9'

services:
  api:
    build: ./apps/api
    container_name: oceanicapescados-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
